FROM ${tribefireBaseImage}

#if ( ${enableGosu} )
RUN apt-get update &&\
    apt-get install -y gosu &&\
    chmod +s $(which gosu) &&\
    rm -rf /var/lib/apt/lists/*
#end

#if ( ${customInstructionsBeforeAddingAssets} )
${customInstructionsBeforeAddingAssets}
#end

COPY webapps/${webappName}/ /opt/tribefire/runtime/host/webapps/ROOT/

#if ( ${pluginsProvided} )
#foreach( $pluginFolderName in ${pluginFolderNames} )
COPY plugins/${pluginFolderName}/ /opt/tribefire/plugins/${pluginFolderName}/
#end
#end

#if ( ${modulesProvided} )
COPY modules/ /opt/tribefire/modules/
#end

#if ( ${tribefirePropertiesProvided} )
COPY environment/tribefire.properties /opt/tribefire/conf/tribefire.properties
#end

#if ( ${rewriteConfigProvided} )
COPY rewrite.config /opt/tribefire/runtime/host/conf/Catalina/localhost/rewrite.config
#end

#if ( ${setupInfoProvided} )
COPY setup-info/ /opt/tribefire/setup-info/
#end

#if ( ${storageProvided} )
COPY storage/ /opt/tribefire/storage/
#end

#if ( ${customInstructionsAfterAddingAssets} )
${customInstructionsAfterAddingAssets}
#end

## 2023-07-10 installing 'wkhtmltopdf' package via custom instructions on Debian Bookworm reset permissions of the home folder.
## To fix this, grant permissions again after running customing instructions.
RUN chmod -R g=u /home/

#if ( !${enableRootPermissions} )
RUN chmod -R ug+rw /opt/tribefire/
## see https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html
RUN echo "default:x:1001:0:default user:/home/:/sbin/nologin" >> /etc/passwd
## user switch is done as the last step
#end

ARG FULLY_QUALIFIED_IMAGE='<unknown>'
RUN echo "****************************************************" &&\
    echo "*** Image Info for Image ${FULLY_QUALIFIED_IMAGE}" &&\
    ls -la / &&\
    ls -la /home/ &&\
    ls -la /opt/tribefire/runtime/host/webapps/ROOT/WEB-INF/lib/ &&\
    (! ${storageProvided} || (ls -la /opt/tribefire/storage/ && find /opt/tribefire/storage)) &&\
    (! ${modulesProvided} || (ls -la /opt/tribefire/modules/ && find /opt/tribefire/modules)) &&\
    (! ${pluginsProvided} || (ls -la /opt/tribefire/plugins/ && find /opt/tribefire/plugins)) &&\
    (! ${tribefirePropertiesProvided} || (cat /opt/tribefire/conf/tribefire.properties)) &&\
    (! ${rewriteConfigProvided} || (cat /opt/tribefire/runtime/host/conf/Catalina/localhost/rewrite.config)) &&\
    echo "*** End of Image Info for Image ${FULLY_QUALIFIED_IMAGE}" &&\
    echo "****************************************************"

## 2025-03-12 /var/lib/dpkg/triggers/Lock exists even in debian base image (in addition to other lock files such as /var/lib/dpkg/lock-frontend and /var/lib/dpkg/lock)
## but this file can only be read by the user itself, not the group, which is a problem when copying to /writable folder (see read-only-root-file-system).
RUN chmod g+r var/lib/dpkg/triggers/Lock

## move relevant paths to a temporary location from where they will (at startup) be copied to a writable folder
RUN /prepare-for-read-only-root-file-system && rm /prepare-for-read-only-root-file-system

#if ( !${enableRootPermissions} )
USER 1001
#end