#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INST_DIR=$DIR/../

if [ -z "${JAVA_HOME}" ]; then
    # JAVA_HOME not set (or empty) --> let's hope 'java' is on the PATH
    JAVA_EXECUTABLE=java
else
    # JAVA_HOME set --> use 'java' command from there
    JAVA_EXECUTABLE="${JAVA_HOME}/bin/java"
fi

SHARED_LIB_PATH=$INST_DIR/../shared-lib
PRIVATE_LIB_PATH=$INST_DIR/lib

if [ -d "$PRIVATE_LIB_PATH" ]; then
    LIB_PATH=$PRIVATE_LIB_PATH
elif [ -d "$SHARED_LIB_PATH" ]; then
    LIB_PATH=$SHARED_LIB_PATH
else
    echo "could not find any of: "
    echo "  $PRIVATE_LIB_PATH"
    echo "  $SHARED_LIB_PATH"
    exit 1
fi

"$JAVA_EXECUTABLE" $JINNI_OPTS -Djinni.installationDir="$INST_DIR" -Dgm.ownCl=true -jar "$LIB_PATH/launch.jar" "$@"
